name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
      - uses: cachix/cachix-action@v15
        with:
          name: wascaml
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix build .
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
      - uses: cachix/cachix-action@v15
        with:
          name: wascaml
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix flake check --all-systems

