name: Generate Documents

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
      - uses: cachix/cachix-action@v15
        with:
          name: wascaml
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix profile install nixpkgs#nodejs
      - name: build documents
        run: |
          nix build ".#docs"
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./result/share/doc
          destination_dir: .
          keep_files: true

